springdoc:
  swagger-ui:
    path: /api-test  # swagger-ui ?? ??? ?? ??, ?? ??? ???? http://localhost:8080/swagger-ui/index.html? ????? ?.
    groups-order: DESC # path, query, body, response ??? ??
    tags-sorter: alpha # ??? ??? ??? ??
    operations-sorter: method # delete - get - patch - post - put ??? ??, alpha? ???? ??? ??? ?? ??
    disable-swagger-default-url: true #Swagger? ?? URL(/swagger-ui/index.html)? ???????. ???? ?? ??(/api-test)? ????? ??? ? ????.
    display-request-duration: true #Swagger UI?? API ?? ? ?? ?? ??? ?????.
    defaultModelsExpandDepth: 2 #Swagger UI?? ?? ??? ????? ???? ??? ?????.
    defaultModelExpandDepth: 2 #?? ?? ??? ?? ?? ??? ?????. ??? ??? ??? ?? ??? ?????.
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**
